In [1]:
import numpy as np
import fpair
import bpair
from diff import diff

In [2]:
n = 4
low, high = 1, 10
arr = np.random.randint(low=low, high=high, size=n, dtype=np.uint32).reshape((n//2, 2))

# arr = np.array([[1,15], [3,7]], dtype=np.uint32)

z = fpair.pair(arr)
z

array([50,  8], dtype=uint64)

In [3]:
n = 200000
low, high = 1, 150
arr_a = np.random.randint(low=low, high=high, size=n, dtype=np.uint32).reshape((n//2, 2))
arr_b = np.random.randint(low=low, high=high, size=n, dtype=np.uint32).reshape((n//2, 2))

In [8]:
diff(arr_a, arr_b, bpair, diff_pos='left')

array([[  3,  33],
       [ 70,  70],
       [ 79,  79],
       [132, 132]], dtype=uint32)

In [9]:
diff(arr_a, arr_b, fpair, diff_pos='left')

array([[  3,  33],
       [ 70,  70],
       [ 79,  79],
       [132, 132]], dtype=uint32)

In [7]:
%timeit diff(arr_a, arr_b, fpair, diff_pos='right')

3.53 s ± 49.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%timeit diff(arr_a, arr_b, bpair, diff_pos='right')

800 ms ± 9.87 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
